/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;
import control.*;
import domain.Guerreiro;
import java.awt.Cursor;
import java.util.LinkedList;
/**
 *
 * @author Paulo Henrique
 */
public class Principal extends javax.swing.JFrame {
    private LinkedList<Guerreiro> lado1;
    private LinkedList<Guerreiro> lado2;
    private MetodosJogo jogo;
    /**
     * Creates new form Principal
     * @param lado1
     * @param lado2
     */
    public Principal(LinkedList<Guerreiro> lado1,LinkedList<Guerreiro> lado2){
        initComponents();
        setLocationRelativeTo(null);
        this.lado1 = lado1;
        this.lado2 = lado2;
    }

    public Principal(){
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInformacoes = new javax.swing.JLabel();
        lblSair = new javax.swing.JLabel();
        lblMostraG = new javax.swing.JLabel();
        lblJogar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblImagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(536, 469));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(null);

        lblInformacoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Informacoes.png"))); // NOI18N
        lblInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInformacoesMouseClicked(evt);
            }
        });
        getContentPane().add(lblInformacoes);
        lblInformacoes.setBounds(10, 300, 64, 40);

        lblSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair.png"))); // NOI18N
        lblSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSairMouseClicked(evt);
            }
        });
        getContentPane().add(lblSair);
        lblSair.setBounds(20, 350, 64, 70);

        lblMostraG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Guerreiros.png"))); // NOI18N
        lblMostraG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMostraGMouseClicked(evt);
            }
        });
        getContentPane().add(lblMostraG);
        lblMostraG.setBounds(10, 10, 130, 130);

        lblJogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ataque.png"))); // NOI18N
        lblJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblJogarMouseClicked(evt);
            }
        });
        getContentPane().add(lblJogar);
        lblJogar.setBounds(210, 150, 130, 120);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("JOGAR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 270, 60, 30);

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("SAIR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 380, 50, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Guerreiros");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 150, 100, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Informações");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(90, 314, 120, 20);

        lblImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoPrincipal.jpg"))); // NOI18N
        getContentPane().add(lblImagem);
        lblImagem.setBounds(0, 0, 520, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void lblSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSairMouseClicked
        System.exit(0);        
    }//GEN-LAST:event_lblSairMouseClicked

    private void lblInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInformacoesMouseClicked
       jogo = new MetodosJogo();
       int maiorIdade = jogo.maisVelho(lado1, lado2);
       int somas[] = new int[2]; 
       somas = jogo.somarPeso(lado1, lado2);
       Informacao info = new Informacao(null,true,maiorIdade,somas);
       info.setVisible(true);
       somas[0] = 0;
       somas[1] = 0;
    }//GEN-LAST:event_lblInformacoesMouseClicked

    private void lblMostraGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMostraGMouseClicked
        Tabela tabela = new Tabela(null,true,lado1,lado2);
        tabela.setVisible(true);
    }//GEN-LAST:event_lblMostraGMouseClicked

    private void lblJogarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblJogarMouseClicked
        Jogo tabuleiro = new Jogo(null,true,lado1,lado2);
        tabuleiro.setVisible(true);
    }//GEN-LAST:event_lblJogarMouseClicked

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        cursorDentro();
    }//GEN-LAST:event_formMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        cursorFora();
    }//GEN-LAST:event_formMouseEntered
     
    private void cursorDentro(){
      this.setCursor(Cursor.HAND_CURSOR); 
    }
    
    private void cursorFora(){
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblImagem;
    private javax.swing.JLabel lblInformacoes;
    private javax.swing.JLabel lblJogar;
    private javax.swing.JLabel lblMostraG;
    private javax.swing.JLabel lblSair;
    // End of variables declaration//GEN-END:variables
}
