/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package windows;

import domain.Guerreiro;
import java.awt.Cursor;
import java.util.LinkedList;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Paulo Henrique
 */
public class Tabela extends javax.swing.JDialog {
    
    /**
     * Creates new form Tabela
     * @param parent
     * @param modal
     */
    public Tabela(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    } 
    
    public Tabela(java.awt.Frame parent, boolean modal,LinkedList<Guerreiro> lado1,LinkedList<Guerreiro> lado2) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        exibe(lado1,lado2);
    }
    
    private void exibe(LinkedList<Guerreiro> lado1,LinkedList<Guerreiro> lado2){
        DefaultTableModel modelTabela1 = (DefaultTableModel) this.tblGuerreiro1.getModel();      
        for(int i = 0; i < lado1.size() && lado1.get(i) != null; i++){
            modelTabela1.addRow(new Object[]{lado1.get(i).getNome(), lado1.get(i).toString()});
        }      
        DefaultTableModel modelTabela2 = (DefaultTableModel) this.tblGuerreiro2.getModel();
        for(int i = 0; i < lado2.size() && lado2.get(i) != null; i++){
            modelTabela2.addRow(new Object[]{lado2.get(i).getNome(), lado2.get(i).toString()});
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblGuerreiro1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblGuerreiro2 = new javax.swing.JTable();
        lblVoltar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FundoTable = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tabela");
        setMinimumSize(new java.awt.Dimension(595, 389));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        getContentPane().setLayout(null);

        tblGuerreiro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        tblGuerreiro1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tblGuerreiro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Lado 1", "Tipo Lado 1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblGuerreiro1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 43, 270, 260);

        tblGuerreiro2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 255)));
        tblGuerreiro2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        tblGuerreiro2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Lado 2", "Tipo Lado 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblGuerreiro2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(299, 43, 270, 260);

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Voltar.png"))); // NOI18N
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });
        getContentPane().add(lblVoltar);
        lblVoltar.setBounds(10, 310, 40, 40);

        jLabel1.setFont(new java.awt.Font("Malgun Gothic Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Guerreiros e suas Classes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 290, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("VOLTAR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 320, 50, 20);

        FundoTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoPrincipal.jpg"))); // NOI18N
        getContentPane().add(FundoTable);
        FundoTable.setBounds(0, 0, 580, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        cursorFora();
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
        cursorDentro();
    }//GEN-LAST:event_formMouseExited
    
    private void cursorDentro(){
      this.setCursor(new Cursor(Cursor.HAND_CURSOR));
      
    }  
    private void cursorFora(){
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Tabela dialog = new Tabela(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FundoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTable tblGuerreiro1;
    private javax.swing.JTable tblGuerreiro2;
    // End of variables declaration//GEN-END:variables

    
}
